[global]
step_threshold                 0.00002
first_step_threshold           0.00002
############### G.8275.1 TELECOM PROFILE ################
network_transport              L2
delay_mechanism                P2P      
#time_stamping                  hardware
tx_timestamp_timeout           40
#clientOnly                     1
# Telecom Profile domain
domainNumber                   24
clientOnly                     1

# Clock identity parameters for Master
priority1                      6
priority2                      128
clockClass                     6
clockAccuracy                  0x20
offsetScaledLogVariance        0xFFFF

############### G.8275.1 MESSAGE INTERVALS ##############
# Sync:     −4 = 16/sec
logSyncInterval                -4

# Announce: −3 = 8 sec
logAnnounceInterval            -3

# Delay_Req / Pdelay_Req: −3 = 8/sec
logMinDelayReqInterval         -3
logMinPdelayReqInterval        -3

############### INTERFACE ################################
[enp1s0f0np0]
transportSpecific              0x0
delay_mechanism                P2P
